# Generated by Django 5.0.6 on 2024-06-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actor',
        ),
    ]
