# Generated by Django 5.0.6 on 2024-08-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_actors_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
